// Auto Dev Orchestrator (simulation)
// Roles: Architect -> Programmer -> Reviewer -> Tester
// This script simulates a lightweight automated pipeline for the Bien Nien Su Viet project.

const fs = require('fs');
const path = require('path');

function ensureDir(p){
  if(!fs.existsSync(p)) fs.mkdirSync(p, {recursive:true});
}

function writeDoc(p, content){
  ensureDir(path.dirname(p));
  fs.writeFileSync(p, content, 'utf8');
}

function archDraft(){
  const now = new Date().toISOString();
  const gdd = `# Game Design Document (BD)

- Project: Bien Nien Su Viet
- Genre: Educational historical strategy / narrative game
- Target: mobile + web
- Core Gameplay: turn-based timeline exploration with knowledge progression

## Core Gameplay
- Timeline-basedKnowledge points unlock eras
- Map system with historical events

## Player Progression
- Knowledge Points -> unlock eras -> unlock features

## Timeline Structure
- Events with timestamp, type, data
- Timeline UI per scene

## Narrative & Narrator
- Narrator system to present historical narration

## Resources & Economy
- Basic resource model: knowledge, coins

## Win Condition
- Reach final era or achieve all historical milestones

---
Generated by AutoDev Architect on ${now}`;
  return gdd;
}

function techDraft(){
  const now = new Date().toISOString();
  const tech = `# TECH OVERVIEW

- Stack: Cocos2d-js 3.x, ES5, HTML5 Canvas
- Modules: game/scenes, game/systems, game/ui, game/data
- TimelineMap: localStorage persistence
- EventSystem: Pub/Sub for game events
- Build notes: relies on localDev environment; prepared for CI integration

---
Generated by AutoDev Architect on ${now}`;
  return tech;
}

function tasksDraft(){
  const now = new Date().toISOString();
  const tasks = `# TASKS

1. Implement Timeline Map System data model and UI glue
2. Build Event System (pub/sub) and integrate with Timeline
3. Create DemoTimelineScene to verify flow
4. Persist timeline via localStorage with key bienniensuviet.timeline
5. Document usage in docs/GDD.md, docs/TECH.md, docs/TASKS.md

Note: This is a lightweight scaffold for automated playtest.

Generated by AutoDev Architect on ${now}`;
  return tasks;
}

const base = path.resolve('D:\workspace\CCN2\bienniensuviet');
writeDoc(path.join(base, 'docs', 'GDD.md'), archDraft());
writeDoc(path.join(base, 'docs', 'TECH.md'), techDraft());
writeDoc(path.join(base, 'docs', 'TASKS.md'), tasksDraft());

console.log('AutoDevArchitect: Docs generated under docs/ (GDD.md, TECH.md, TASKS.md)');
